name: "FRP Client Addon (smartify.lv)"
description: "You can use this tool to achieve remote access to local Home Assistant"
version: "1.0.1"
slug: "frp_client_smartify"
host_network: true
startup: application
boot: "auto"
init: false
map:
  - "share:rw"
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  serverAddr: "xxxx.xx.clients.smartify.lv"
#  serverPort: 7000
  remotePort: 8101
#  authToken: "SecretToken"
#  webServerPort: 7500
#  webServerUser: "admin"
#  webServerPassword: "WebPass"
#  proxyName: "homeassistant"
schema:
  serverAddr: str
#  serverPort: int
  remotePort: int
#  authToken: str
#  webServerPort: int
#  webServerUser: str
#  webServerPassword: str
#  proxyName: str
