serverAddr = ""
serverPort = 7000
auth.method = "token"
auth.token = ""

log.to = "/share/frpc.log"
log.level = "trace"
log.maxDays = 3

[[proxies]]
name = ""
type = "tcp"
transport.useEncryption = true
transport.useCompression = true
remotePort = 
localPort = 8123
localIP = "0.0.0.0"
